### ISSUE TITLE
checkbox not showing up in 2.6-pl

### ISSUE THREAD

**Issue by Lefthandmedia** [Jako/MODX-ForcedPasswdChange#3]
Hi,
I cant find the checkbox to set force change in 2.6-pl
RDG

**Comment by bertoost** [comment]
Probably because it's very old and not really maintained anymore ;-)

**Comment by Lefthandmedia** [comment]
Well thats a shame. actually i think it should be build into MODX core. the possibilitie to force people to change their pwd is vital in todays security measures.
